apiVersion: v1
kind: Service
metadata:
  name: house-inference-api
  namespace: {{ .Values.namespace }}
  labels:
    app: house-inference-api
spec:
  selector:
    app: house-inference-api
  ports:
    - name: http
      port: 80
      targetPort: 8989
      protocol: TCP
  type: ClusterIP
