apiVersion: v1
kind: Service
metadata:
  name: house-streamlit
  namespace: {{ .Values.namespace }}
  labels:
    app: house-streamlit
spec:
  selector:
    app: house-streamlit
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: {{ .Values.streamlit.nodePort }}
      protocol: TCP
  type: NodePort
