apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<TU_USUARIO>/<TU_REPO>.git
    targetRevision: main
    path: argocd/apps  # carpeta donde pondrás las subaplicaciones

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
